### ISSUE TITLE
Tool correction: goDiamond

### ISSUE THREAD

**Issue by hstrass** [TimKam/fantastic-arg-tools#3]
Thanks for listing our tool goDiamond! I have the following suggestions for changes:

- License: GPL v3 as stated in branch go, file `go/src/diamond/diamond.go`
- Last change: 2017-06-26 (branch go)
- Logic Solver Approach: ASP solver
- Argumentation Approach: Abstract Dialectical Frameworks

**Comment by TimKam** [comment]
Thank you, @hstrass! Here is my update: https://github.com/TimKam/fantastic-arg-tools/pull/4/files. Let me know in case you still see any issues there; otherwise, I'll merge.
